### ISSUE TITLE
How can I remove the wrapper around the input

### ISSUE THREAD

**Issue by krishnagupta21** [Azure/InferenceSchema#31]
I have a simple schema as shown below. I want to use it as it is without a wrapper around it. Is there a way to not wrap the input inside this "data" wrapper?

Here is what my score.py looks like:
```
input_sample = {
                "id": 123,
                "language": "en"
                "items": [{
                    "item": 1,
                    "desc": "desc"
                }]
            }
output_sample = [{'prediction': 'true', 'predictionConfidence': 0.8279970776764844}]

@input_schema('data', StandardPythonParameterType(input_sample))
@output_schema(StandardPythonParameterType(output_sample))
def run(data):
"""
    {
        data: { --> DON'T WANT this "data" wrapper
                "id": 123,
                "language": "en"
                "items": [{
                    "item": 1,
                    "desc": "desc"
                }]
            }
    }
    """
    try:
        id = data['id']
        ...
```

**Comment by trangevi** [comment]
The short answer is no, there isn't a way to remove that wrapper layer.
 
The longer answer is the package is designed to account for multiple input parameters to the decorated function. In that case, the swagger document needs to specify things based on the different parameters, so that the caller of the function can pass to appropriate values to the appropriate parameters. There have been some brief discussions about potentially changing things for single parameter functions, but I'm not sure it's a good idea to have too much variance based purely on number of inputs, as having different behavior cases inevitably leads to confusion.
